@server = https://super-invention-rrpgjv5wj3xj56-8080.app.github.dev
###
GET {{server}}/api/instrumentos
###
POST {{server}}/api/instrumentos
Content-Type: application/json

{"nombre": "Quena", "categoria": "Viento", "descripcion": "Como una flauta"}
###
GET {{server}}/api/musicos
###
POST {{server}}/api/musicos
Content-Type: application/json

{"nombre": "Joaquín"}



